// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yerpdyaywkivputvolat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllcnBkeWF5d2tpdnB1dHZvbGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjMwNjYsImV4cCI6MjA2NTEzOTA2Nn0.TW10EcuC-mFl13ZrLth72b-xF6-d5uQN7In2uXQs_dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);